name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  measure_execution:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3,4,5,6,7,8]
        shardTotal: [8]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0    
    - name: Check changes in test folder
      id: folder_changes
      run: |
        changes=$(git diff --name-only origin/main -- tests/)
        if [ -n "$changes" ]; then
            echo "Changes detected in 'tests/' folder."
            echo "::set-output name=changed::true"
        else
            echo "No changes detected in 'tests/' folder."
            echo "::set-output name=changed::false"
        fi  
    - name: Set shardIndex environment variable
      run: echo 'SHARD_INDEX=${{ matrix.shardIndex }}' >> $GITHUB_ENV          
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      if: steps.folder_changes.outputs.changed == 'true'
      run: npm install
    - name: Install Playwright Browsers
      if: steps.folder_changes.outputs.changed == 'true'
      run: npx playwright install
    - name: Run Playwright tests
      if: steps.folder_changes.outputs.changed == 'true'
      run: |
        MEASURE_EXECUTION_TIME=true npx playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }} --repeat-each=1
    - name: Upload JSON File
      if: steps.folder_changes.outputs.changed == 'true'
      uses: actions/upload-artifact@v2
      with:
        name: test_execuction_results
        path: test_execuction_results_${{ matrix.shardIndex }}.json
  combine_test_execution_result:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs:
      - measure_execution
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: |
        if [[ -f test_execuction_results.json ]]; then
            rm test_execuction_results.json
        fi 
    - name: Download JSON File
      uses: actions/download-artifact@v3
      with:
        name: test_execuction_results
        path: .  
    - uses: sergeysova/jq-action@v2
      with:
        cmd: jq -s '[.[][]]' test_execuction_results_*.json > test_execuction_results.json
    - run: rm test_execuction_results_*.json  
    - uses: actions/upload-artifact@v2
      with:
        name: test_execuction_results
        path: test_execuction_results.json              
    - name: Commit Json File
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
         commit_message: 'Update Execution Time file'
         file_pattern: "*.json"   
  test_smart_orchestration:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs:
      - measure_execution
      - combine_test_execution_result
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3]
        shardTotal: [3]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: test_execuction_results
        path: .
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Set shardTotal environment variable
      run: echo "SHARD_TOTAL=${{ matrix.shardTotal }}" >> $GITHUB_ENV     
    - name: Install dependencies
      run: npm install
    - name: Install Playwright Browsers
      run: npx playwright install
    - name: Get test names
      id: getTestNames
      run: |
        npx tsc ./utils/smart-orchestration-github.ts
        test_names=$(node ./utils/smart-orchestration-github.js ${{ matrix.shardIndex }})
        echo "::set-output name=test_names::$test_names"
    - name: Run Playwright tests
      run: |
          npx playwright test --grep "${{ steps.getTestNames.outputs.test_names }}"
  test_no_orcestration:
    needs:
      - test_smart_orchestration
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          shardIndex: [1, 2, 3]
          shardTotal: [3]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Set shardTotal environment variable
        run: echo "shardTotal=${{ matrix.shardTotal }}" >> $GITHUB_ENV     
      - name: Install dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install
      - name: Run Playwright tests
        run: |
         npx playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}                   

        

    
